package org.kde.necessitas.industrius;

import android.app.Activity;
import android.app.Dialog;
import android.content.Context;
import android.content.Intent;
import android.content.res.Configuration;
import android.content.res.Resources.Theme;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.os.Bundle;
import android.util.AttributeSet;
import android.view.ContextMenu;
import android.view.ContextMenu.ContextMenuInfo;
import android.view.KeyEvent;
import android.view.Menu;
import android.view.MenuItem;
import android.view.MotionEvent;
import android.view.View;
import android.view.WindowManager.LayoutParams;

public interface QtActivityListener
{
	void onActivityResult(int requestCode, int resultCode, Intent data);
	void onApplyThemeResource(Theme theme, int resid, boolean first);
	void onAttachedToWindow();
	void onBackPressed();
	void onChildTitleChanged(Activity childActivity, CharSequence title);
	void onConfigurationChanged(Configuration newConfig);
	void onContentChanged();
	boolean onContextItemSelected(MenuItem item);
	void onContextMenuClosed(Menu menu);
	void onCreate(Bundle savedInstanceState);
	void onCreateContextMenu(ContextMenu menu, View v, ContextMenuInfo menuInfo);
	CharSequence onCreateDescription();
	Dialog onCreateDialog(int id);
	Dialog onCreateDialog(int id, Bundle args);
	boolean onCreateOptionsMenu(Menu menu);
	boolean onCreatePanelMenu(int featureId, Menu menu);
	View onCreatePanelView(int featureId);
	boolean onCreateThumbnail(Bitmap outBitmap, Canvas canvas);
	View onCreateView(String name, Context context, AttributeSet attrs);
	void onDestroy();
	void onDetachedFromWindow();
	boolean onKeyDown(int keyCode, KeyEvent event);
	boolean onKeyLongPress(int keyCode, KeyEvent event);
	boolean onKeyMultiple(int keyCode, int repeatCount, KeyEvent event);
	boolean onKeyUp(int keyCode, KeyEvent event);
	void onLowMemory();
	boolean onMenuItemSelected(int featureId, MenuItem item);
	boolean onMenuOpened(int featureId, Menu menu);
	void onNewIntent(Intent intent);
	boolean onOptionsItemSelected(MenuItem item);
	void onOptionsMenuClosed(Menu menu);
	void onPanelClosed(int featureId, Menu menu);
	void onPause();
	void onPostCreate(Bundle savedInstanceState);
	void onPostResume();
	void onPrepareDialog(int id, Dialog dialog);
	void onPrepareDialog(int id, Dialog dialog, Bundle args);
    boolean onPrepareOptionsMenu(Menu menu);
    boolean onPreparePanel(int featureId, View view, Menu menu);
    void onRestart();
    void onRestoreInstanceState(Bundle savedInstanceState);
    void onResume();
    Object onRetainNonConfigurationInstance();
    void onSaveInstanceState(Bundle outState);
    boolean onSearchRequested();
    void onStart();
    void onStop();
    void onTerminate();
    void onTitleChanged(CharSequence title, int color);
    boolean onTrackballEvent(MotionEvent event);
    void onUserInteraction();
    void onUserLeaveHint();
    void onWindowAttributesChanged(LayoutParams params);
    void onWindowFocusChanged(boolean hasFocus);
}
